### ISSUE TITLE
Excessive DataTables warnings

### ISSUE THREAD

**Issue by hadro** [ryanfb/book-aligner#24]
Performed a search for this volume: https://archive.org/details/analecticmagazi01irvigoog

And got back dozens of datatables popup warning messages similar to the below that had to be confirmed before being allowed to continue loading the page. In the end, I got the results, but it was a hairy experience in both Firefox (59.0.2 (64-bit)) and Chrome (Version 66.0.3359.139 (Official Build) (64-bit)), both on a Macbook Air.

`DataTables warning: table id=table - Requested unknown parameter '3' for row 68, column 3. For more information about this error, please see http://datatables.net/tn/4`

**Comment by ryanfb** [comment]
Thanks for the heads-up! I'll investigate and see if I can figure out what's going on to make a fix.

**Comment by ryanfb** [comment]
Seems to be fixed by 4397c9a72f9a2f0fc2dee1fad529c1b98e374297. Please let me know if there's still problems!

**Comment by hadro** [comment]
Amazing, thank you for the quick fix! 
Your tool is really invaluable for the volunteer reference work I do with HathiTrust, among other things!
